GraceChurchKelseyvilleAwana/Models/GroupsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GraceChurchKelseyvilleAwana.Models
{
    public class GroupsViewModel
    {
        public ApplicationUser[] Leaders { get; set; }
    }

    public class GroupingViewModel
    {
        /*public ApplicationUser Leader { get; set; }
        public List<Student> UnassignedStudents { get; set; }*/

        public ApplicationUser Leader { get; set; }
        public List<StudentCheckBox> AssignedStudents { get; set; }
        public List<StudentCheckBox> UnassignedStudents { get; set; }
    }

    public class StudentCheckBox
    {
        public bool IsChecked { get; set; }
        public Student student { get; set; }
    }
}

GraceChurchKelseyvilleAwana/Controllers/GroupsController.cs
using GraceChurchKelseyvilleAwana.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraceChurchKelseyvilleAwana.Controllers
{
    public class GroupsController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        //
        // GET: /Groups/
        public ActionResult Index()
        {
            var leaders = GetLeaders();
            return View(new GroupsViewModel { Leaders = leaders });
        }

        //
        // GET: /Groups/Grouping/id
        public ActionResult Grouping(string id)
        {
            var leader = db.Users.First(x => x.Id.Equals(id));

            var assignedStudents = new List<StudentCheckBox>();
            foreach(var student in leader.Students.OrderBy(x => x.LastName).ThenBy(x => x.FirstName))
            {
                assignedStudents.Add(new StudentCheckBox { student = student });
            }
            var unassignedStudents = new List<StudentCheckBox>();
            foreach(var student in db.Students.Where(x => x.Leader == null).OrderBy(x => x.LastName).ThenBy(x => x.FirstName))
            {
                unassignedStudents.Add(new StudentCheckBox { student = student });
            }

            return View(new GroupingViewModel { Leader = leader, AssignedStudents = assignedStudents, UnassignedStudents = unassignedStudents });
        }

        public ApplicationUser[] GetLeaders()
        {
            var leaders = new List<ApplicationUser>();

            foreach (var user in db.Users)
            {
                if (user.Role.Equals(AwanaRoles.Leader))
                {
                    leaders.Add(user);
                }
            }

            return leaders.ToArray();
        }

        [HttpPost]
        public ActionResult Assign(GroupingViewModel vm)
        {
            foreach (var student in vm.UnassignedStudents.Where(x => x.IsChecked))
            {
                var actualStudent = db.Students.First(x => x.StudentID == student.student.StudentID);
                actualStudent.LeaderID = vm.Leader.Id;
            }
            db.SaveChanges();
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }

        [HttpPost]
        public ActionResult Unassign(GroupingViewModel vm)
        {
            foreach (var student in vm.AssignedStudents.Where(x => x.IsChecked))
            {
                var actualStudent = db.Students.First(x => x.StudentID == student.student.StudentID);
                actualStudent.LeaderID = null;
            }
            db.SaveChanges();
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
	}
}

GraceChurchKelseyvilleAwana/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GraceChurchKelseyvilleAwana.Models;
using PagedList;

namespace GraceChurchKelseyvilleAwana.Controllers
{
    public class StudentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private const int STUDENT_PAGE_SIZE = 10;

        // GET: /Student/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, Int32? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            var students = GetAvailableStudents();

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.LastName.ToUpper().Contains(searchString.ToUpper())
                    || s.FirstName.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.LastName).ThenBy(s => s.FirstName);
                    break;
                default:
                    students = students.OrderBy(s => s.LastName).ThenBy(s => s.FirstName);
                    break;
            }

            int pageSize = STUDENT_PAGE_SIZE;

            //If not logged in do this:
            //return RedirectToAction("Index", "Home");
            return View(students.ToPagedList((page ?? 1), pageSize));
        }

        public IQueryable<Student> GetAvailableStudents()
        {
            var students = from s in db.Students select s;
            if (User.IsInRole(AwanaRoles.Leader.ToString()))
            {
                var user = ApplicationUser.GetFromUserIdentity(User.Identity);
                students = students.Where(x => x.LeaderID.Equals(user.Id));
            }
            else if (User.IsInRole(AwanaRoles.Admin.ToString()))
            {
                //Admin gets all students
            }
            else if (User.IsInRole(AwanaRoles.Director.ToString()))
            {
                // TODO: Add directors implementation
                //accessibleStudents = db.Students.ToList();
            }
            else if (User.IsInRole(AwanaRoles.Parent.ToString()))
            {
                // TODO: Add parents implementation
                //accessibleStudents = db.Students.ToList();
            }

            return students;
        }

        // GET: /Student/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: /Student/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Student/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentID,FirstName,LastName,BirthDate,Grade,Gender,MedicalInformation,EmailAddress")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(student);
        }

        // GET: /Student/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: /Student/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentID,FirstName,LastName,BirthDate,Grade,Gender,MedicalInformation,EmailAddress")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: /Student/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: /Student/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GraceChurchKelseyvilleAwana/Views/Groups/Grouping.cshtml
@model GraceChurchKelseyvilleAwana.Models.GroupingViewModel

@{
    ViewBag.Title = "Grouping";
}

<h2>Grouping</h2>

<h3>@Model.Leader.FullName()</h3>

@if (Model.AssignedStudents.Count() > 0)
{ 
    using (Html.BeginForm("Unassign", "Groups", FormMethod.Post))
    { 
        <table class="table-condensed">
            @for (int i = 0; i < @Model.AssignedStudents.Count(); i++ )
            {
                <tr>
                    <td>
                        @Html.CheckBoxFor(x => x.AssignedStudents[i].IsChecked, new { @id = "student_" + i })
                        @Html.HiddenFor(x => x.AssignedStudents[i].student.StudentID)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x.AssignedStudents.ElementAt(i).student.BothNames)
                    </td>
                </tr>
        
            }
        </table>
        <input type="submit" value="Unassign" class="btn btn-default" />
    }
}
else
{
    <text>This leader has no students.</text>
}

<h3>Unassigned Students</h3>

@if (Model.UnassignedStudents.Count > 0)
{
    using (Html.BeginForm("Assign", "Groups", FormMethod.Post))
    { 
        <table class="table-condensed">
            @for (int i = 0; i < @Model.UnassignedStudents.Count; i++)
            {
                <tr>
                    <td>
                        @Html.CheckBoxFor(x => x.UnassignedStudents[i].IsChecked, new { @id = "student_" + i })
                        @Html.HiddenFor(x => x.UnassignedStudents[i].student.StudentID)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x.UnassignedStudents[i].student.BothNames)
                    </td>
                </tr>
            }
        </table>
        @Html.HiddenFor(x => x.Leader.Id)
        <input type="submit" value="Assign" class="btn btn-default" />
        
    }
}
else
{
    <text>All students are currrently assigned to a leader.</text>
}

GraceChurchKelseyvilleAwana/Views/Groups/Index.cshtml
@model GraceChurchKelseyvilleAwana.Models.GroupsViewModel


@{
    ViewBag.Title = "Groups";
}

<h2>Groups</h2>

<table class="table-bordered" cellpadding="10">
    <tr>
        <th>
            Leaders
        </th>
        <th>
            Students
        </th>
    </tr>
    @foreach (var leader in Model.Leaders)
    {
        <tr>
            <td>
                @Html.ActionLink((string)leader.FullName(), "Grouping", new { @id = leader.Id })
            </td>
            <td>
                @for (int i = 0; i < leader.Students.Count; i++)
                {
                    var student = leader.Students.ElementAt(i);
                    @Html.ActionLink(student.BothNames, "Details", "Student", new { @id = student.StudentID }, null)
                    if (i + 1 < leader.Students.Count)
                    {
                        <text>, </text>
                    }
                }
            </td>
        </tr>
    }
</table>
