GraceChurchKelseyvilleAwana/Controllers/EmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GraceChurchKelseyvilleAwana.Models;
using GraceChurchKelseyvilleAwana.Email;
using System.Threading.Tasks;

namespace GraceChurchKelseyvilleAwana.Controllers
{
    public class EmailController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Email/
        public ActionResult Index(bool confirm = false)
        {
            return View(new EmailViewModel { Confirm = confirm });
        }

        [HttpPost]
        public ActionResult Index(EmailViewModel vm)
        {
            if (vm.Recipients.Equals("Leaders"))
            {
                EmailLeaders(vm);
            }
            else if (vm.Recipients.Equals("Students"))
            {
                EmailStudents(vm);
            }

            return RedirectToAction("Index", new { @confirm = true });
        }

        //TODO: Add full implementation
        private void EmailStudents(EmailViewModel vm)
        {
            foreach (var student in db.Students.Where(s => !string.IsNullOrEmpty(s.EmailAddress)))
            {
                EmailHelper.SendEmail("Grace Church Awana Announcement", vm.EmailBody, student.EmailAddress);
            }
        }

        //TODO: Add full implementation
        private void EmailLeaders(EmailViewModel vm)
        {
            foreach(var leader in db.Users.Where(s => !string.IsNullOrEmpty(s.EmailAddress)))
            {
                EmailHelper.SendEmail("Grace Church Awana Announcement", vm.EmailBody, leader.EmailAddress);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
	}
}

GraceChurchKelseyvilleAwana/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GraceChurchKelseyvilleAwana.Models;
using PagedList;

namespace GraceChurchKelseyvilleAwana.Controllers
{
    public class StudentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private const int STUDENT_PAGE_SIZE = 10;

        // GET: /Student/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, Int32? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            var students = GetAvailableStudents();

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.LastName.ToUpper().Contains(searchString.ToUpper())
                    || s.FirstName.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.LastName).ThenBy(s => s.FirstName);
                    break;
                default:
                    students = students.OrderBy(s => s.LastName).ThenBy(s => s.FirstName);
                    break;
            }

            int pageSize = STUDENT_PAGE_SIZE;

            //If not logged in do this:
            //return RedirectToAction("Index", "Home");
            return View(students.ToPagedList((page ?? 1), pageSize));
        }

        public IQueryable<Student> GetAvailableStudents()
        {
            var students = from s in db.Students select s;
            if (User.IsInRole(AwanaRoles.Leader.ToString()))
            {
                var user = ApplicationUser.GetFromUserIdentity(User.Identity);
                students = students.Where(x => x.LeaderID.Equals(user.Id));
            }
            else if (User.IsInRole(AwanaRoles.Admin.ToString()))
            {
                //Admin gets all students
            }
            else if (User.IsInRole(AwanaRoles.Director.ToString()))
            {
                // TODO: Add directors implementation
                //accessibleStudents = db.Students.ToList();
            }
            else if (User.IsInRole(AwanaRoles.Parent.ToString()))
            {
                // TODO: Add parents implementation
                //accessibleStudents = db.Students.ToList();
            }

            return students;
        }

        // GET: /Student/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: /Student/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Student/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentID,FirstName,LastName,BirthDate,Grade,Gender,MedicalInformation,EmailAddress")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(student);
        }

        // GET: /Student/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: /Student/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentID,FirstName,LastName,BirthDate,Grade,Gender,MedicalInformation,EmailAddress")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: /Student/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: /Student/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GraceChurchKelseyvilleAwana/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Grace Church Kelseyville Awana</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Grace Church Kelseyville Awana", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--<li>@Html.ActionLink("Home", "Index", "Home")</li>-->
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                    <li>@Html.ActionLink("Attendance", "Index", "Attendance")</li>
                    <li>@Html.ActionLink("Sections", "Progress", "Sections")</li>
                    @if (User.IsInRole(GraceChurchKelseyvilleAwana.Models.AwanaRoles.Admin.ToString()))
                    {
                        <li>@Html.ActionLink("Books", "Index", "Sections")</li>
                        <li>@Html.ActionLink("Groups", "Index", "Groups")</li>
                        <li>@Html.ActionLink("Manage Roles", "Roles", "Account")</li>
                        <li>@Html.ActionLink("Emailing", "Index", "Email")</li>
                    }
                    <!--<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>-->
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <a href="http://gracechurchkelseyville.org">Grace Church Kelseyville</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>