GraceChurchKelseyvilleAwana/Models/Sections/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GraceChurchKelseyvilleAwana.Models.Sections
{
    public class Book
    {
        [Key]
        public string BookID { get; set; }
        public AgeGroups AgeGroup { get; set; }

        public virtual ICollection<Chapter> Chapters { get; set; }
    }
}

GraceChurchKelseyvilleAwana/Models/Sections/Chapter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GraceChurchKelseyvilleAwana.Models.Sections
{
    public class Chapter
    {
//        [Key, Column(Order=1)]
        public string BookID { get; set; }

//        [Key, Column(Order=0)]
        public int ChapterID { get; set; }

        public virtual Book Book { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}

GraceChurchKelseyvilleAwana/Models/Sections/Section.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GraceChurchKelseyvilleAwana.Models.Sections
{
    public class Section
    {
        public int SectionID { get; set; }

        public int ChapterID { get; set; }

        public string BookID { get; set; }

        public virtual Chapter Chapter { get; set; }

        public virtual ICollection<SectionCompletion> Completions { get; set; }
    }
}

GraceChurchKelseyvilleAwana/Models/SectionsViewModels.cs
using GraceChurchKelseyvilleAwana.Models.Sections;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GraceChurchKelseyvilleAwana.Models
{
    public class IndexSectionsViewModel
    {
        public List<Book> Books { get; set; }
    }

    public class SectionsProgressListingViewModel
    {
        public List<Student> Students { get; set; }
    }

    public class TrackProgressViewModel
    {
        public List<BookCheckList> Books { get; set; }
        public Student Student { get; set; }
    }

    public class SectionCheckList
    {
        public Section Section { get; set; }
        public bool Completed { get; set; }
    }

    public class ChapterCheckList
    {
        public List<SectionCheckList> Sections { get; set; }
        public int ChapterNumber { get; set; }
    }

    public class BookCheckList
    {
        public List<ChapterCheckList> Chapters { get; set; }
        public string Title { get; set; }
    }
}

GraceChurchKelseyvilleAwana/Controllers/SectionsController.cs
using GraceChurchKelseyvilleAwana.Models;
using GraceChurchKelseyvilleAwana.Models.Sections;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraceChurchKelseyvilleAwana.Controllers
{
    public class SectionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //
        // GET: /Sections/Index
        public ActionResult Index()
        {
            if (!User.IsInRole(AwanaRoles.Admin.ToString()))
            {
                return RedirectToAction("Index", "Home");
            }

            return View(new IndexSectionsViewModel { Books = db.Books.ToList() });
        }

        //
        // GET: /Sections/Progress
        public ActionResult Progress()
        {
            var students = db.StudentsUserHasAccessTo(User);

            return View(new SectionsProgressListingViewModel { Students = students });
        }

        //
        // GET: /Sections/TrackProgress/studentID
        public ActionResult TrackProgress(int id)
        {
            var books = db.Books.ToList();
            var student = db.Students.First(s => s.StudentID == id);
            var completedSections = student.SectionsCompleted;

            var bookCheckList = new List<BookCheckList>();
            foreach (var book in books)
            {
                var chapterCheckList = new List<ChapterCheckList>();
                foreach (var chapter in book.Chapters)
                {
                    var sectionCheckList = new List<SectionCheckList>();
                    foreach(var section in chapter.Sections)
                    {
                        sectionCheckList.Add(new SectionCheckList { Section = section, Completed = completedSections.FirstOrDefault(c => c.Section.Equals(section)) != null});
                    }
                    chapterCheckList.Add(new ChapterCheckList { ChapterNumber = chapter.ChapterID, Sections = sectionCheckList});
                }
                bookCheckList.Add(new BookCheckList { Title = book.BookID, Chapters = chapterCheckList});
            }

            return View(new TrackProgressViewModel { Books = bookCheckList, Student = student });
        }

        [HttpPost]
        public ActionResult TrackProgress(TrackProgressViewModel vm)
        {
            var allSections = vm.Books.SelectMany(b => b.Chapters.SelectMany(c => c.Sections));
            var completedSections = allSections.Where(s => s.Completed);
            var student = db.Students.First(s => s.StudentID == vm.Student.StudentID);

            foreach(var completedSection in completedSections)
            {
                var sectionCompletion = ToSectionCompletion(completedSection, student);

                if (student.SectionsCompleted.FirstOrDefault(s => s.BookID.Equals(sectionCompletion.BookID) && s.ChapterID == sectionCompletion.ChapterID && s.SectionID == sectionCompletion.SectionID) == null)
                {

                    student.SectionsCompleted.Add(sectionCompletion);
                }
            }

            db.SaveChanges();

            return RedirectToAction("Progress");
        }



        public SectionCompletion ToSectionCompletion(SectionCheckList selectionCheckList, Student student)
        {
            var Section = db.Sections.First(s => s.BookID.Equals(selectionCheckList.Section.BookID) && s.ChapterID == selectionCheckList.Section.ChapterID && s.SectionID == selectionCheckList.Section.SectionID);
            return new SectionCompletion { Student = student, BookID = Section.BookID, ChapterID = Section.ChapterID, SectionID = Section.SectionID, StudentID = student.StudentID, DateCompleted = DateTime.Today };
        }

        //
        // GET: /Sections/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Sections/Create()
        [HttpPost]
        public ActionResult Create(FormCollection form)
        {
            var chapters = form.AllKeys.Where(s => s.Contains("section"));
            var numChapters = chapters.Count();
            string bookName = form.GetValue("bookName").AttemptedValue;

            var book = new Book { BookID = bookName, AgeGroup = (AgeGroups)Enum.Parse(typeof(AgeGroups), form.GetValue("ageGroup").AttemptedValue, true) };
            db.Books.Add(book);
            
            var counter = 1;
            foreach (var chapter in chapters)
            {
                var dbChapter = new Chapter { BookID = book.BookID, ChapterID = counter++ };
                db.Chapters.Add(dbChapter);

                int numSections = int.Parse(form.GetValue(chapter).AttemptedValue);
                for (int i = 0; i < numSections; i++)
                {
                    db.Sections.Add(new Section { ChapterID = dbChapter.ChapterID, BookID = dbChapter.BookID, SectionID = i + 1 });
                }
            }
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //
        // GET: /Sections/Delete/bookId
        [HttpGet]
        public ActionResult Delete(string bookId)
        {
            db.Books.Remove(db.Books.Find(bookId));
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
	}
}

GraceChurchKelseyvilleAwana/Views/Sections/Create.cshtml

@{
    ViewBag.Title = "Create";
}

<h2>Create Book</h2>

@using (Html.BeginForm("Create", "Sections", FormMethod.Post, new { @id = "myForm" }))
{
    <div class="form-horizontal">
        <hr/>
        <div class="form-group">
            @Html.Label("Title", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="bookName" id="bookName" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Age Group", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="ageGroup" class="dropdown">
                    @foreach (var group in Enum.GetNames(typeof(GraceChurchKelseyvilleAwana.Models.AgeGroups)))
                    {
                        <option value=@group>@group.ToString()</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Number of Chapters", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="number" min="1" id="numberOfRows" />
                <input type="button" name="GenerateTableButton" value="Change" onclick="onGenerateTableButtonClick()" />
            </div>
        </div>
    </div>

    <table id="chaptersTable" class="table-bordered col-md-offset-2" cellpadding="15">
        <tr>
            <th>
                Chapter
            </th>
            <th>
                Number of Sections
            </th>
        </tr>
    </table>

    <br />
    <br />
        
    <input id="submitButton" type="button" value="Save" class="btn btn-default" onclick="checkFormAndSubmit()" disabled="disabled"/>

        <script type="text/javascript" src="@Url.Content("/Scripts/CreateBooks.js")" ></script>

    <script type="text/javascript" language="javascript">
        function onGenerateTableButtonClick() {
            var table = document.getElementById("chaptersTable");
            var rowNumString = document.getElementById("numberOfRows").value;
            var rowNum = +rowNumString;

            if (isNaN(rowNum) || rowNum < 1)
            {
                alert("Number of chapters must be a number greater than 0");
            }
            else
            {
                while (table.rows.length > 1)
                {
                    table.deleteRow(1);
                }
                var counter = 0;
                while (table.rows.length <= rowNum)
                {
                    var row = table.insertRow(table.rows.length);
                    var cell1 = row.insertCell(0);
                    cell1.align = "center";
                    var chapterNumber = document.createElement("text");
                    chapterNumber.textContent = "" + table.rows.length - 1;
                    cell1.appendChild(chapterNumber);
                    var cell2 = row.insertCell(1);
                    var sectionInput = document.createElement("input");
                    sectionInput.id = "section_" + table.rows.length - 1;
                    sectionInput.name = "section[" + counter++ + "]";
                    sectionInput.type = "number";
                    sectionInput.min = "1";
                    sectionInput.value = "1";
                    cell2.appendChild(sectionInput);
                }
                document.getElementById("submitButton").disabled = false;
            }
        }
    </script>
}




GraceChurchKelseyvilleAwana/Views/Sections/Index.cshtml
@model GraceChurchKelseyvilleAwana.Models.IndexSectionsViewModel


@{
    ViewBag.Title = "Edit";
}

<h2>Edit Books</h2>

<p>
    @Html.ActionLink("Create New Book", "Create")
</p>

@foreach (var book in Model.Books)
{
    <table class="table-condensed">
        <tr>
            <td valign="baseline">
                <h3>
                    @Html.DisplayFor(modelItem => book.BookID)
                </h3>
            </td>
            <td valign="baseline">
                @Html.ActionLink("Delete", "Delete", new { bookId = book.BookID} )
            </td>
        </tr>
    </table>
    <table class="table-condensed" border="1" style="margin-left:25px">
        <tr>
            <th>
                <b>Chapter</b>
            </th>
            <th>
                <b>Number of Sections</b>
            </th>
        </tr>
        @foreach (var chapter in book.Chapters)
        {
            <tr>
                <td align="center">
                    @chapter.ChapterID
                </td>
                <td align="center">
                    @chapter.Sections.Count
                </td>
            </tr>
        }
    </table>
}


GraceChurchKelseyvilleAwana/Views/Sections/Progress.cshtml
@model GraceChurchKelseyvilleAwana.Models.SectionsProgressListingViewModel

@{
    ViewBag.Title = "Progress";
}

<h2>Sections Progress</h2>

<table class="table-bordered" cellpadding="15">
    @foreach (var student in Model.Students)
    {
        <tr>
            <td>
                @Html.DisplayFor(item => student.BothNames)
            </td>
            <td>
                @Html.ActionLink("Track Progress", "TrackProgress", new { @id = student.StudentID })
            </td>
        </tr>
    }
</table>

GraceChurchKelseyvilleAwana/Views/Sections/TrackProgress.cshtml
@model GraceChurchKelseyvilleAwana.Models.TrackProgressViewModel

@{
    ViewBag.Title = "TrackProgress";
}

<h2>@Model.Student.BothNames's Progress</h2>

@using (Html.BeginForm("TrackProgress", "Sections", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Student.StudentID)
    
    <div class="row">
        @for (int i = 0; i < Model.Books.Count; i++)
        {
            <div class="col-md-2">
                <h3>@Model.Books[i].Title</h3>
                @Html.HiddenFor(model => model.Books[i].Title)

                @for (int j = 0; j < Model.Books[i].Chapters.Count; j++)
                {
                    <h4 style="margin-left:10px">Chapter @Model.Books[i].Chapters[j].ChapterNumber</h4>
                    @Html.HiddenFor(model => model.Books[i].Chapters[j].ChapterNumber)

                    for (int k = 0; k < Model.Books[i].Chapters[j].Sections.Count; k++)
                    {
                        <div style="margin-left:30px">
                            @Html.CheckBoxFor(model => model.Books[i].Chapters[j].Sections[k].Completed)
                            Section @Model.Books[i].Chapters[j].Sections[k].Section.SectionID
                            <br />
                            @Html.HiddenFor(model => model.Books[i].Chapters[j].Sections[k].Section.BookID)
                            @Html.HiddenFor(model => model.Books[i].Chapters[j].Sections[k].Section.ChapterID)
                            @Html.HiddenFor(model => model.Books[i].Chapters[j].Sections[k].Section.SectionID)
                        </div>
                    }
                }
            </div>
        }
    </div>

    <input type="submit" value="Save" class="btn btn-default" style="margin-top:25px" />
}


